energyData <- read.csv("./data/household_power_consumption.txt")
dates_times <- paste(energyData[,1],energyData[,2])
x <- strptime(dates_times, "%d/%m/%Y %I:%M:%S %p")
par(mfrow=c(2,2))
png("./data/plot3.png")
plot(x,energyData$Global_active_power,type="l",ylab="Global Active Power",xlab=" ",yaxt="n",cex.lab=0.7)
y <- c(0:6)
axis(2,at=y,labels=y,cex.axis=.7)
plot(x,energyData$Voltage,type="l",ylab="Voltage",xlab="datetime",yaxt="n",cex.lab=0.7)
y <- c(234:246)
axis(2,at=y,labels=y,cex.axis=.7)
y1 <- energyData$Sub_metering_1
y2 <- energyData$Sub_metering_2
y3 <- energyData$Sub_metering_3
plot(x,y1,type="l",ylab="Energy sub metering",xlab=" ",yaxt="n",cex.lab=0.7)
y <- c(0,10,20,30)
axis(2,at=y,labels=y,cex.axis=.7)
lines(x,y2,type="l",ylab="Energy sub metering",xlab=" ",col="red")
lines(x,y3,type="l",ylab="Energy sub metering",xlab=" ",col="blue")
leg.txt <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
legend("topright",leg.txt,lty=1,col=c(1,2,4),bty="n",cex=.25)
plot(x,energyData$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime",yaxt="n",cex.lab=0.7)
y <- c(0,0.1,0.2,0.3,0.4,0.5)
axis(2,at=y,labels=y,cex.axis=.6)
dev.off()